package com.is.tf.sign;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.rpc.Service;
import javax.xml.rpc.ServiceFactory;

import javax.xml.rpc.handler.*;

import org.zkoss.zhtml.A;

import java.util.*;

// watch here at the package used to
// store the RcxReadLS class generated
// by the WSDL2Java tool
//import rcxwsclient.sei.RcxReadLS;

public class ClientSEI {

  public static void main(String[] args) 

  {
		
    try {
	  
 	  QName serviceName = new QName(
		"http://phonedirlux.homeip.net/wsdl",
		"MyRcxService");
          
  	  URL wsdlLocation = new URL
		("http://www.pascalbotte.be:80/rcx-ws-rpc/rcx?WSDL");

          // Service
  	  	ServiceFactory factory = ServiceFactory.newInstance();
  	  	Service service = factory.createService(
		wsdlLocation,
		serviceName);

          HandlerRegistry hr = service.getHandlerRegistry();

          QName  portName = new QName("http://phonedirlux.homeip.net/wsdl", "RcxReadLSPort");

          List handlerChain = hr.getHandlerChain(portName);

          HandlerInfo hi = new HandlerInfo();
          hi.setHandlerClass(AABankMessageLogger.class);
          handlerChain.add(hi);
		
          // Service Endpoint Interface class generated by WSDL2Java					
  	  //RcxReadLS objRcx = (RcxReadLS) service.getPort(portName, RcxReadLS.class);
					
  	  //String val = objRcx.readLS("Your message here, with eventually your e-mail address");
	  //System.out.println("Rcx web service message: " + val);

	}
    catch (Throwable t) {
      t.printStackTrace();
    }
  }
}
