/**
 * BankService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.sbs.service;

public interface BankService extends java.rmi.Remote {
    public com.sbs.service.PolicyResult getPolicy(java.lang.String bankInn, java.lang.String p1T1, java.lang.String p3T32) throws java.rmi.RemoteException;
    public com.sbs.service.CommissionGNKResult getCommissionGNK(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p9T28) throws java.rmi.RemoteException;
    public com.sbs.service.CommissionsGNKResult getCommissionsGNK(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.CommissionGNKResult saveCommissionGNK(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.CommissionGNK commissionGNK) throws java.rmi.RemoteException;
    public com.sbs.service.TransferResult confirmTransfer(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p8T29, java.lang.Short action, java.lang.String fio) throws java.rmi.RemoteException;
    public com.sbs.service.DelegateResult confirmDelegate(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p20T30, java.lang.Short action, java.lang.String fio) throws java.rmi.RemoteException;
    public com.sbs.service.PolicyTimeChangeResult savePolicyTimeChange(java.lang.String bankInn, java.lang.String p1T1, java.lang.String p3T32, com.sbs.service.PolicyTimeChange policyTimeChange) throws java.rmi.RemoteException;
    public com.sbs.service.PolicySumChangeResult savePolicySumChange(java.lang.String bankInn, java.lang.String p1T1, java.lang.String p3T32, com.sbs.service.PolicySumChange policySumChange) throws java.rmi.RemoteException;
    public com.sbs.service.PaymentsRefResult getPaymentsRef(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.PaymentRefResult savePaymentRef(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.PaymentRef paymentRef) throws java.rmi.RemoteException;
    public com.sbs.service.PaymentRefSumChangeResult savePaymentRefSumChange(java.lang.String bankInn, java.lang.String p1T1, java.lang.String p2T37, com.sbs.service.PaymentRefSumChange paymentRefSumChange) throws java.rmi.RemoteException;
    public com.sbs.service.CompensationResult getCompensation(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p15T42) throws java.rmi.RemoteException;
    public com.sbs.service.CompensationsResult getCompensations(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.CompensationResult saveCompensation(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Compensation compensation) throws java.rmi.RemoteException;
    public com.sbs.service.MovesFromImResult getMovesFromIm(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.MovesFromExResult getMovesFromEx(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.Record1Result dicAgreementState(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicBenefitsInfo(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicBenefitsType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicIndustrialZone(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicContractSubject(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record5Result dicContractType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicPaymentSource(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicPenaltyType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicTransferType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record3Result dicPaymentMethod(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicTransportType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record3Result dicEnterpriseType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicServiceType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record6Result dicRecordState(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.ContractResult getContract(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.ContractResult getHistory(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.GarantResult getGarant(java.lang.String bankInn, java.lang.String p1T1, java.lang.String p3T18) throws java.rmi.RemoteException;
    public com.sbs.service.GarantsResult getGarants(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.GarantResult saveGarant(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Garant garant) throws java.rmi.RemoteException;
    public com.sbs.service.AccreditivResult getAccreditiv(java.lang.String bankInn, java.lang.String p1T1, java.lang.String p2T21) throws java.rmi.RemoteException;
    public com.sbs.service.DebetResult getDebet(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p13T24) throws java.rmi.RemoteException;
    public com.sbs.service.DebetsResult getDebets(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.DebetResult saveDebet(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Debet debet) throws java.rmi.RemoteException;
    public com.sbs.service.CreditResult getCredit(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p13T25) throws java.rmi.RemoteException;
    public com.sbs.service.CreditsResult getCredits(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.CreditResult saveCredit(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Credit credit) throws java.rmi.RemoteException;
    public com.sbs.service.PenaltyResult getPenalty(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p7T26) throws java.rmi.RemoteException;
    public com.sbs.service.PenaltiesResult getPenalties(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.PenaltyResult savePenalty(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Penalty penalty) throws java.rmi.RemoteException;
    public com.sbs.service.CommissionResult getCommission(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p6T27) throws java.rmi.RemoteException;
    public com.sbs.service.DebetInfoResult getDebetInfo(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p7T31) throws java.rmi.RemoteException;
    public com.sbs.service.DebetsInfoResult getDebetsInfo(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.DebetInfoResult saveDebetInfo(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.DebetInfo debetInfo) throws java.rmi.RemoteException;
    public com.sbs.service.PoliciesResult getPolicies(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.PolicyResult savePolicy(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Policy policy) throws java.rmi.RemoteException;
    public com.sbs.service.FundResult getFund(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p2T35) throws java.rmi.RemoteException;
    public com.sbs.service.FundsResult getFunds(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.FundResult saveFund(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Fund fund) throws java.rmi.RemoteException;
    public com.sbs.service.RefundExpResult getRefundExp(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p13T36) throws java.rmi.RemoteException;
    public com.sbs.service.RefundsExpResult getRefundsExp(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.RefundExpResult saveRefundExp(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.RefundExp refundExp) throws java.rmi.RemoteException;
    public com.sbs.service.PaymentRefResult getPaymentRef(java.lang.String bankInn, java.lang.String p1T1, java.lang.String p2T37) throws java.rmi.RemoteException;
    public com.sbs.service.TaxResult getTax(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p11T39) throws java.rmi.RemoteException;
    public com.sbs.service.TaxesResult getTaxes(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.TaxResult saveTax(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Tax tax) throws java.rmi.RemoteException;
    public com.sbs.service.MoveToExResult getMoveToEx(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p33T40) throws java.rmi.RemoteException;
    public com.sbs.service.MovesToExResult getMovesToEx(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.MoveToExResult saveMoveToEx(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.MoveToEx moveToEx) throws java.rmi.RemoteException;
    public com.sbs.service.SaleResult getSale(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p26T43) throws java.rmi.RemoteException;
    public com.sbs.service.SalesResult getSales(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.SaleResult saveSale(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Sale sale) throws java.rmi.RemoteException;
    public com.sbs.service.PaymentResult getPayment(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p22T44) throws java.rmi.RemoteException;
    public com.sbs.service.PaymentsResult getPayments(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.PaymentResult savePayment(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Payment payment) throws java.rmi.RemoteException;
    public com.sbs.service.RefundImpResult getRefundImp(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p12T45) throws java.rmi.RemoteException;
    public com.sbs.service.RefundsImpResult getRefundsImp(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.RefundImpResult saveRefundImp(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.RefundImp refundImp) throws java.rmi.RemoteException;
    public com.sbs.service.MoveToImResult getMoveToIm(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p36T47) throws java.rmi.RemoteException;
    public com.sbs.service.MovesToImResult getMovesToIm(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.MoveToImResult saveMoveToIm(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.MoveToIm moveToIm) throws java.rmi.RemoteException;
    public com.sbs.service.LeaseResult getLease(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p5T50) throws java.rmi.RemoteException;
    public com.sbs.service.LeasesResult getLeases(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.LeaseResult saveLease(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Lease lease) throws java.rmi.RemoteException;
    public com.sbs.service.MoveFromImResult getMoveFromIm(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p29T53) throws java.rmi.RemoteException;
    public com.sbs.service.MoveFromExResult getMoveFromEx(java.lang.String bankInn, java.lang.String p1T1, java.lang.Integer p23T52) throws java.rmi.RemoteException;
    public com.sbs.service.Result saveConfirm(java.lang.String bankInn, java.lang.String contractIdn, java.lang.String docType, java.lang.String docNum, java.lang.String chDocNum, java.lang.Short confirm, java.lang.String reason, java.lang.String responsibleName) throws java.rmi.RemoteException;
    public com.sbs.service.DicVersionResult dicVersions(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.RecordResult dicRefer(java.lang.String bankInn, java.lang.String name) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicBasis(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicCarryType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicConditions(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record3Result dicCountry(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record3Result dicBank(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicDebetModes(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record4Result dicErrors(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record4Result dicGnk(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record3Result dicYeisDocs(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicExportType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record5Result dicIncoterms(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record3Result dicPost(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicSaleReason(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicSaleSource(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicSaleType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicReasons(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record3Result dicRegions(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicFundSource(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicFundType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicFundDest(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record3Result dicTnved(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicGoodsType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record5Result dicUnit(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record3Result dicService(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record2Result dicLoanType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record3Result dicDealType(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.Record3Result dicProc(java.lang.String bankInn) throws java.rmi.RemoteException;
    public com.sbs.service.ContractStatusResult getContractStatus(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.ContractsResult getContractsByInn(java.lang.String bankInn, java.lang.String clientInn) throws java.rmi.RemoteException;
    public com.sbs.service.GarantSumChangeResult saveGarantSumChange(java.lang.String bankInn, java.lang.String p1T1, java.lang.String p3T18, com.sbs.service.GarantSumChange garantSumChange) throws java.rmi.RemoteException;
    public com.sbs.service.GarantTimeChangeResult saveGarantTimeChange(java.lang.String bankInn, java.lang.String p1T1, java.lang.String p3T18, com.sbs.service.GarantTimeChange garantTimeChange) throws java.rmi.RemoteException;
    public com.sbs.service.AccreditivesResult getAccreditives(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.AccreditivResult saveAccreditiv(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Accreditiv accreditiv) throws java.rmi.RemoteException;
    public com.sbs.service.AccreditivSumChangeResult saveAccreditivSumChange(java.lang.String bankInn, java.lang.String p1T1, java.lang.String p2T21, com.sbs.service.AccreditivSumChange accreditivSumChange) throws java.rmi.RemoteException;
    public com.sbs.service.AccreditivTimeChangeResult saveAccreditivTimeChange(java.lang.String bankInn, java.lang.String p1T1, java.lang.String p2T21, com.sbs.service.AccreditivTimeChange accreditivTimeChange) throws java.rmi.RemoteException;
    public com.sbs.service.CommissionsResult getCommissions(java.lang.String bankInn, java.lang.String p1T1) throws java.rmi.RemoteException;
    public com.sbs.service.CommissionResult saveCommission(java.lang.String bankInn, java.lang.String p1T1, com.sbs.service.Commission commission) throws java.rmi.RemoteException;
}
