package com.is.nibbd.util;



public enum NibbdFields {
	BRANCH, NUMERIC_ID, QUERY_NUM, STR_NUM, REIS_NUM, ID_CLIENT,
	RESIDENT, NAME, CODE_COUNTRY, NUMBER_REGISTRATION_DOC, PLACE_REGIST_NAME,
	DATE_REGISTRATION, NUMBER_TAX_REGISTRATION, CODE_HEAD_ORGANIZATION,
	INN_HEAD_ORGANIZATION, CODE_SUBJECT, CODE_TYPE_CYR, OPF, CODE_FORM,
	SOATO, OKPO, CODE_SECTOR, REASONING, ACC_BAL, CURRENCY, ID_ORDER, OLD_ACC,
	NEW_ACC, REGION, DISTRICT, QUERY_DATE, QUERY_INP, QUERY_OUT, PARENT_ID,
	STATE;
}
