package com.is.clients.utils;

public enum ClientFields {
    ID(false, false),
    BRANCH(false, true),
    ID_CLIENT(true, false),
    ID_CLIENT_IN_SAP(false, false),
    ID_SAP(false, false),
    NAME(true, true),
    CODE_COUNTRY(true, true),
    CODE_COUNTRY1(true, true),
    CODE_TYPE(true, true),
    CODE_RESIDENT(true, true),
    CODE_RESIDENT1(true, true),
    CODE_SUBJECT(true, false),
    SIGN_REGISTR(false, false),
    CODE_FORM(true, true),
    DATE_OPEN(false, false),
    DATE_CLOSE(false, false),
    STATE(false, false),
    KOD_ERR(false, false),
    FILE_NAME(false, false),
    J_SHORT_NAME(false, true),
    J_PLACE_REGIST_NAME(true, true),
    J_DATE_REGISTRATION(true, true),
    J_NUMBER_REGISTRATION_DOC(true, true),
    J_CODE_TAX_ORG(false, true),
    J_NUMBER_TAX_REGISTRATION(true, true),
    J_CODE_SECTOR(true, true),
    J_CODE_SECTOR_OLD(false, true),
    J_CODE_ORGAN_DIRECT(false, true),
    J_CODE_HEAD_ORGANIZATION(true, true),
    J_CODE_CLASS_CREDIT(false, true),
    J_DIRECTOR_NAME(false, true),
    J_DIRECTOR_PASSPORT(false, true),
    J_CHIEF_ACCOUNTER_NAME(false, true),
    J_CHIEF_ACCOUNTER_PASSPORT(false, true),
    J_CODE_BANK(false, false),
    J_ACCOUNT(false, false),
    J_POST_ADDRESS(false, true),
    J_PHONE(false, true),
    J_FAX(false, true),
    J_EMAIL(false, true),
    J_SIGN_TRADE(false, true),
    J_OPF(true, true),
    J_SOATO(true, true),
    J_OKPO(true, true),
    J_INN_HEAD_ORGANIZATION(true, true),
    J_REGION(true, true),
    J_DISTR(true, true),
    J_SMALL_BUSINESS(false, true),
    J_DIRECTOR_TYPE_DOCUMENT(false, true),
    J_DIRECTOR_PASSP_SERIAL(false, true),
    J_DIRECTOR_PASSP_NUMBER(false, true),
    J_DIRECTOR_PASSP_DATE_REG(false, true),
    J_DIRECTOR_PASSP_PLACE_REG(false, true),
    J_DIRECTOR_PASSP_DATE_END(false, true),
    J_DIRECTOR_CODE_CITIZENSHIP(false, true),
    J_DIRECTOR_BIRTHDAY(false, true),
    J_DIRECTOR_BIRTH_PLACE(false, true),
    J_DIRECTOR_ADDRESS(false, true),
    J_ACCOUNTANT_TYPE_DOCUMENT(false, true),
    J_ACCOUNTANT_PASSP_SERIAL(false, true),
    J_ACCOUNTANT_PASSP_NUMBER(false, true),
    J_ACCOUNTANT_PASSP_DATE_REG(false, true),
    J_ACCOUNTANT_PASSP_PLACE_REG(false, true),
    J_ACCOUNTANT_PASSP_DATE_END(false, true),
    J_ACCOUNTANT_CODE_CITIZENSHIP(false, true),
    J_ACCOUNTANT_BIRTHDAY(false, true),
    J_ACCOUNTANT_BIRTH_PLACE(false, true),
    J_ACCOUNTANT_ADDRESS(false, true),
    J_327(false, false),
    J_PATENT_EXPIRATION(false, true),
    J_RESPONSIBLE_EMP(false, false),
    J_SIGN_VIP(false, false),
    P_BIRTHDAY(false, true),
    P_POST_ADDRESS(false, true),
    P_PASSPORT_TYPE(false, true),
    P_PASSPORT_SERIAL(false, true),
    P_PASSPORT_NUMBER(false, true),
    P_PASSPORT_PLACE_REGISTRATION(false, true),
    P_PASSPORT_DATE_REGISTRATION(false, true),
    P_CODE_TAX_ORG(false, true),
    P_NUMBER_TAX_REGISTRATION(false, true),
    P_CODE_BANK(false, true),
    P_CODE_CLASS_CREDIT(false, true),
    P_CODE_CITIZENSHIP(false, true),
    P_BIRTH_PLACE(false, true),
    P_CODE_CAPACITY(false, true),
    P_CAPACITY_STATUS_DATE(false, true),
    P_CAPACITY_STATUS_PLACE(false, true),
    P_NUM_CERTIF_CAPACITY(false, true),
    P_PHONE_HOME(false, true),
    P_PHONE_MOBILE(false, true),
    P_EMAIL_ADDRESS(false, true),
    P_PENSION_SERTIF_SERIAL(false, true),
    P_CODE_GENDER(false, true),
    P_CODE_NATION(false, true),
    P_CODE_BIRTH_REGION(false, true),
    P_CODE_BIRTH_DISTR(false, true),
    P_TYPE_DOCUMENT(false, true),
    P_PASSPORT_DATE_EXPIRATION(false, true),
    P_CODE_ADR_REGION(false, true),
    P_CODE_ADR_DISTR(false, true),
    P_INPS(false, true),
    P_PINFL(true, true),
    P_FAMILY(false, true),
    P_FIRST_NAME(false, true),
    P_PATRONYMIC(false, true),
    P_SIGN_VIP(false, true),
    P_LAST_NAME_CYR(false, true),
    P_FIRST_NAME_CYR(false, true),
    P_PATRONYMIC_CYR(false, true),
    I_SHORT_NAME(false, true),
    I_DATE_REGISTRATION(false, true),
    I_NUMBER_REGISTRATION_DOC(false, true),
    I_PLACE_REGIST_NAME(false, true),
    I_NUMBER_TAX_REGISTRATION(false, true),
    I_OPF(false, true),
    I_FORM(false, true),
    I_SECTOR(false, true),
    I_ORGAN_DIRECT(false, true),
    I_ACCOUNT(false, true),
    I_POST_ADDRESS(false, true),
    I_DIRECTOR_NAME(false, true),
    I_CHIEF_ACCOUNTER_NAME(false, true),
    I_PHONE(false, true),
    I_FAX(false, true),
    I_EMAIL(false, true),
    P_PASS_PLACE_REGION(false, true),
    P_PASS_PLACE_DISTRICT(false, true),
    P_POST_ADDRESS_QUARTER(false, true),
    P_POST_ADDRESS_STREET(false, true),
    P_POST_ADDRESS_HOUSE(false, true),
    P_POST_ADDRESS_FLAT(false, true),
    SIGN_100(false, false),
    J_SIGN_DEP_ACC(false, true),
    CAPITAL_INFORM(false, true),
    CAPITAL_CURRENCY(false, true),
    J_TYPE_ACTIVITY(false,true),
    SWIFT_ID(false,false),
    TYPE_NON_RESIDENT(false,false),
    DIRECTOR(false,false),
    ACCOUNTANT(false,false),
    INDIVIDUALENTERPRENEUR(false,false),
    REGISTRATIONCOUNTRY(false,false),
    NIBBD_EMP_ID(false,false),
    ADDRESSCOUNTRY(false,true),
    DATE_OPEN1(false, false),
    DATE_CLOSE1(false, false),
    POST_ADDRESS_COUNTRY(false, false),
    SIGN_DATE_OPEN(false, false),
    SIGN_DATE_CLOSE(false, false),
    I014(false,false);

    private boolean isObjectiveField;
    private boolean isManual;

    private ClientFields(boolean isObjectiveField) {
        this.isObjectiveField = isObjectiveField;
    }

    private ClientFields(boolean isObjectiveField, boolean isManual) {
        this.isObjectiveField = isObjectiveField;
        this.isManual = isManual;
    }

    public boolean isObjectiveField() {
        return isObjectiveField;
    }

    public boolean isManual() {
        return isManual;
    }
}
