pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["admin.htm","Администрирование","Администрирование",""],
["chapter_2.htm","Kommunal to&#39;lovlar &#62; Hisob raqamlarni sozlash","Hisob raqamlarni sozlash",""],
["introduction.htm","Вход в систему \"МУНИС\"","Вход с систему \"Мунис\"",""],
["munis_ru_content.htm","No title","Руководство пользователя по системе \"МУНИС\" Contents | Index | Search Вход в систему \"МУНИС\" Администрирование Роли Пользователи Коммунальные плат...",""],
["munis_ru_ftsearch.htm","No title","Руководство пользователя по системе \"МУНИС\" Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): ",""],
["munis_ru_kwindex.htm","No title","Руководство пользователя по системе \"МУНИС\" Contents | Index | Search A B C D E F G H I J K L M N O P Q R S T U V W X Y Z ",""],
["munis_uz_ftsearch.htm","No title","Руководство пользователя по системе \"МУНИС\" Contents | Index | Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): ",""],
["payments.htm","Kommunal to&#39;lovlar &#62; To&#39;lovlar","To&#39;lovlar",""],
["roles.htm","Роли","Роли",""],
["topic.htm","Kommunal to&#39;lovlar","Kommunal to&#39;lovlar",""],
["transactionsettings.htm","Коммунальные платежи &#62; Настройка проводок","Настройка проводок",""],
["users.htm","Пользователи","Пользователи",""]];
