refill.surname=Фамилия
refill.name=Имя
refill.birth_date=Дата рождения
refill.client_b=Код клиента в банке
refill.client=Код клиента в Tieto
refill.card=Карта
refill.expiry=Действительна до
refill.tranz_acct=Счет в банке
refill.status=Статус
refill.card_balance=Баланс карты
refill.cards_list=Карты
refill.customers_list=Клиенты
refill.acсounts_list=Счета
refill.card_acct=Номер счета карты
refill.ccy=Валюта счета
refill.account_no=Внутренний номер счета
refill.refill_sum_quastion=Введите сумму пополнения
refill.refill_window=Пополнение
refill.refill_btn=Пополнить
refill.refill_cancel_btn=Отменить
refill.cash_refill=Наличные
refill.cashless_refill=Безналичный рассчет

refillConfirm.card=Номер карты
refillConfirm.transAmnt=Сумма пополнения
refillConfirm.clientName=Имя
refillConfirm.clientSurname=Фамилия
refillConfirm.state=Состояние
refillConfirm.actions=Действия

